// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blacklist.sql

package db

import (
	"context"
)

const addBlacklist = `-- name: AddBlacklist :exec
INSERT INTO blacklist (entity_type, entity_id, added_by) VALUES (?1, ?2, 0) ON CONFLICT (entity_type, entity_id) DO NOTHING
`

type AddBlacklistParams struct {
	EntityType string `json:"entityType"`
	TargetId   int64  `json:"targetId"`
}

func (q *Queries) AddBlacklist(ctx context.Context, arg AddBlacklistParams) error {
	_, err := q.db.ExecContext(ctx, addBlacklist, arg.EntityType, arg.TargetId)
	return err
}

const isBlacklisted = `-- name: IsBlacklisted :one
SELECT EXISTS(
  SELECT 1 FROM blacklist WHERE entity_id = ?1 AND entity_type = ?2
) AS is_blacklisted
`

type IsBlacklistedParams struct {
	EntityId   int64  `json:"entityId"`
	EntityType string `json:"entityType"`
}

func (q *Queries) IsBlacklisted(ctx context.Context, arg IsBlacklistedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isBlacklisted, arg.EntityId, arg.EntityType)
	var is_blacklisted int64
	err := row.Scan(&is_blacklisted)
	return is_blacklisted, err
}

const listBlacklist = `-- name: ListBlacklist :many
SELECT entity_type, entity_id, added_by, added_at
FROM blacklist ORDER BY entity_id
`

func (q *Queries) ListBlacklist(ctx context.Context) ([]Blacklist, error) {
	rows, err := q.db.QueryContext(ctx, listBlacklist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blacklist
	for rows.Next() {
		var i Blacklist
		if err := rows.Scan(
			&i.EntityType,
			&i.EntityID,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBlacklist = `-- name: RemoveBlacklist :exec
DELETE FROM blacklist WHERE entity_id = ?1
`

func (q *Queries) RemoveBlacklist(ctx context.Context, entityid int64) error {
	_, err := q.db.ExecContext(ctx, removeBlacklist, entityid)
	return err
}
