// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drops.sql

package db

import (
	"context"
	"database/sql"
)

const claimDrop = `-- name: ClaimDrop :one
UPDATE drops
SET winner_id = ?, claimed_at = CURRENT_TIMESTAMP
WHERE id = ? AND winner_id IS NULL
RETURNING id, question, answer, xp_amount, winner_id, dropped_by, channel_id, message_id, claimed_at, created_at
`

type ClaimDropParams struct {
	WinnerID sql.NullInt64 `json:"winner_id"`
	ID       int64         `json:"id"`
}

func (q *Queries) ClaimDrop(ctx context.Context, arg ClaimDropParams) (Drop, error) {
	row := q.db.QueryRowContext(ctx, claimDrop, arg.WinnerID, arg.ID)
	var i Drop
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.Answer,
		&i.XpAmount,
		&i.WinnerID,
		&i.DroppedBy,
		&i.ChannelID,
		&i.MessageID,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDrop = `-- name: GetDrop :one
SELECT id, question, answer, xp_amount, winner_id, dropped_by, channel_id, message_id, claimed_at, created_at FROM drops WHERE id = ?
`

func (q *Queries) GetDrop(ctx context.Context, id int64) (Drop, error) {
	row := q.db.QueryRowContext(ctx, getDrop, id)
	var i Drop
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.Answer,
		&i.XpAmount,
		&i.WinnerID,
		&i.DroppedBy,
		&i.ChannelID,
		&i.MessageID,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingDropByMessage = `-- name: GetPendingDropByMessage :one
SELECT id, question, answer, xp_amount, winner_id, dropped_by, channel_id, message_id, claimed_at, created_at FROM drops WHERE message_id = ? AND winner_id IS NULL
`

func (q *Queries) GetPendingDropByMessage(ctx context.Context, messageID sql.NullInt64) (Drop, error) {
	row := q.db.QueryRowContext(ctx, getPendingDropByMessage, messageID)
	var i Drop
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.Answer,
		&i.XpAmount,
		&i.WinnerID,
		&i.DroppedBy,
		&i.ChannelID,
		&i.MessageID,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDrop = `-- name: InsertDrop :one
INSERT INTO drops (question, answer, xp_amount, dropped_by, channel_id, message_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, question, answer, xp_amount, winner_id, dropped_by, channel_id, message_id, claimed_at, created_at
`

type InsertDropParams struct {
	Question  string        `json:"question"`
	Answer    string        `json:"answer"`
	XpAmount  int64         `json:"xp_amount"`
	DroppedBy sql.NullInt64 `json:"dropped_by"`
	ChannelID int64         `json:"channel_id"`
	MessageID sql.NullInt64 `json:"message_id"`
}

func (q *Queries) InsertDrop(ctx context.Context, arg InsertDropParams) (Drop, error) {
	row := q.db.QueryRowContext(ctx, insertDrop,
		arg.Question,
		arg.Answer,
		arg.XpAmount,
		arg.DroppedBy,
		arg.ChannelID,
		arg.MessageID,
	)
	var i Drop
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.Answer,
		&i.XpAmount,
		&i.WinnerID,
		&i.DroppedBy,
		&i.ChannelID,
		&i.MessageID,
		&i.ClaimedAt,
		&i.CreatedAt,
	)
	return i, err
}
