// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: giveaways.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countEntries = `-- name: CountEntries :one
SELECT COUNT(*) FROM giveaway_entries WHERE giveaway_id = ?
`

func (q *Queries) CountEntries(ctx context.Context, giveawayID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntries, giveawayID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEntriesForGiveaway = `-- name: DeleteEntriesForGiveaway :exec
DELETE FROM giveaway_entries WHERE giveaway_id = ?
`

func (q *Queries) DeleteEntriesForGiveaway(ctx context.Context, giveawayID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntriesForGiveaway, giveawayID)
	return err
}

const deleteGiveaway = `-- name: DeleteGiveaway :exec
DELETE FROM giveaways WHERE id = ?
`

func (q *Queries) DeleteGiveaway(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGiveaway, id)
	return err
}

const endGiveaway = `-- name: EndGiveaway :exec
UPDATE giveaways SET ended = 1 WHERE id = ?
`

func (q *Queries) EndGiveaway(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, endGiveaway, id)
	return err
}

const getActiveGiveawayByMessage = `-- name: GetActiveGiveawayByMessage :one
SELECT id, channel_id, message_id, prize, winner_count, required_role, host_id, ends_at, ended, min_level, min_account_days, role_multipliers, created_at FROM giveaways WHERE message_id = ? AND ended = 0
`

func (q *Queries) GetActiveGiveawayByMessage(ctx context.Context, messageID int64) (Giveaway, error) {
	row := q.db.QueryRowContext(ctx, getActiveGiveawayByMessage, messageID)
	var i Giveaway
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.MessageID,
		&i.Prize,
		&i.WinnerCount,
		&i.RequiredRole,
		&i.HostID,
		&i.EndsAt,
		&i.Ended,
		&i.MinLevel,
		&i.MinAccountDays,
		&i.RoleMultipliers,
		&i.CreatedAt,
	)
	return i, err
}

const getGiveaway = `-- name: GetGiveaway :one
SELECT id, channel_id, message_id, prize, winner_count, required_role, host_id, ends_at, ended, min_level, min_account_days, role_multipliers, created_at FROM giveaways WHERE id = ?
`

func (q *Queries) GetGiveaway(ctx context.Context, id int64) (Giveaway, error) {
	row := q.db.QueryRowContext(ctx, getGiveaway, id)
	var i Giveaway
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.MessageID,
		&i.Prize,
		&i.WinnerCount,
		&i.RequiredRole,
		&i.HostID,
		&i.EndsAt,
		&i.Ended,
		&i.MinLevel,
		&i.MinAccountDays,
		&i.RoleMultipliers,
		&i.CreatedAt,
	)
	return i, err
}

const getGiveawayByMessage = `-- name: GetGiveawayByMessage :one
SELECT id, channel_id, message_id, prize, winner_count, required_role, host_id, ends_at, ended, min_level, min_account_days, role_multipliers, created_at FROM giveaways WHERE message_id = ?
`

func (q *Queries) GetGiveawayByMessage(ctx context.Context, messageID int64) (Giveaway, error) {
	row := q.db.QueryRowContext(ctx, getGiveawayByMessage, messageID)
	var i Giveaway
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.MessageID,
		&i.Prize,
		&i.WinnerCount,
		&i.RequiredRole,
		&i.HostID,
		&i.EndsAt,
		&i.Ended,
		&i.MinLevel,
		&i.MinAccountDays,
		&i.RoleMultipliers,
		&i.CreatedAt,
	)
	return i, err
}

const hasEntry = `-- name: HasEntry :one
SELECT COUNT(*) > 0 AS entered FROM giveaway_entries
WHERE giveaway_id = ? AND user_id = ?
`

type HasEntryParams struct {
	GiveawayID int64 `json:"giveaway_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) HasEntry(ctx context.Context, arg HasEntryParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasEntry, arg.GiveawayID, arg.UserID)
	var entered bool
	err := row.Scan(&entered)
	return entered, err
}

const insertEntry = `-- name: InsertEntry :exec
INSERT OR IGNORE INTO giveaway_entries (giveaway_id, user_id) VALUES (?, ?)
`

type InsertEntryParams struct {
	GiveawayID int64 `json:"giveaway_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertEntry, arg.GiveawayID, arg.UserID)
	return err
}

const insertGiveaway = `-- name: InsertGiveaway :one
INSERT INTO giveaways (
    channel_id, message_id, prize, winner_count, required_role, host_id, ends_at,
    min_level, min_account_days, role_multipliers
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, channel_id, message_id, prize, winner_count, required_role, host_id, ends_at, ended, min_level, min_account_days, role_multipliers, created_at
`

type InsertGiveawayParams struct {
	ChannelID       int64         `json:"channel_id"`
	MessageID       int64         `json:"message_id"`
	Prize           string        `json:"prize"`
	WinnerCount     int64         `json:"winner_count"`
	RequiredRole    sql.NullInt64 `json:"required_role"`
	HostID          int64         `json:"host_id"`
	EndsAt          time.Time     `json:"ends_at"`
	MinLevel        int64         `json:"min_level"`
	MinAccountDays  int64         `json:"min_account_days"`
	RoleMultipliers string        `json:"role_multipliers"`
}

func (q *Queries) InsertGiveaway(ctx context.Context, arg InsertGiveawayParams) (Giveaway, error) {
	row := q.db.QueryRowContext(ctx, insertGiveaway,
		arg.ChannelID,
		arg.MessageID,
		arg.Prize,
		arg.WinnerCount,
		arg.RequiredRole,
		arg.HostID,
		arg.EndsAt,
		arg.MinLevel,
		arg.MinAccountDays,
		arg.RoleMultipliers,
	)
	var i Giveaway
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.MessageID,
		&i.Prize,
		&i.WinnerCount,
		&i.RequiredRole,
		&i.HostID,
		&i.EndsAt,
		&i.Ended,
		&i.MinLevel,
		&i.MinAccountDays,
		&i.RoleMultipliers,
		&i.CreatedAt,
	)
	return i, err
}

const listActive = `-- name: ListActive :many
SELECT id, channel_id, message_id, prize, winner_count, required_role, host_id, ends_at, ended, min_level, min_account_days, role_multipliers, created_at FROM giveaways WHERE ended = 0
`

func (q *Queries) ListActive(ctx context.Context) ([]Giveaway, error) {
	rows, err := q.db.QueryContext(ctx, listActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Giveaway
	for rows.Next() {
		var i Giveaway
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.MessageID,
			&i.Prize,
			&i.WinnerCount,
			&i.RequiredRole,
			&i.HostID,
			&i.EndsAt,
			&i.Ended,
			&i.MinLevel,
			&i.MinAccountDays,
			&i.RoleMultipliers,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT user_id FROM giveaway_entries WHERE giveaway_id = ?
`

func (q *Queries) ListEntries(ctx context.Context, giveawayID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, giveawayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredUnended = `-- name: ListExpiredUnended :many
SELECT id, channel_id, message_id, prize, winner_count, required_role, host_id, ends_at, ended, min_level, min_account_days, role_multipliers, created_at FROM giveaways WHERE ended = 0 AND ends_at <= CURRENT_TIMESTAMP
`

func (q *Queries) ListExpiredUnended(ctx context.Context) ([]Giveaway, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredUnended)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Giveaway
	for rows.Next() {
		var i Giveaway
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.MessageID,
			&i.Prize,
			&i.WinnerCount,
			&i.RequiredRole,
			&i.HostID,
			&i.EndsAt,
			&i.Ended,
			&i.MinLevel,
			&i.MinAccountDays,
			&i.RoleMultipliers,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGiveawayMessage = `-- name: UpdateGiveawayMessage :exec
UPDATE giveaways SET message_id = ? WHERE id = ?
`

type UpdateGiveawayMessageParams struct {
	MessageID int64 `json:"message_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateGiveawayMessage(ctx context.Context, arg UpdateGiveawayMessageParams) error {
	_, err := q.db.ExecContext(ctx, updateGiveawayMessage, arg.MessageID, arg.ID)
	return err
}
