// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leaderboard.sql

package db

import (
	"context"
)

const getWeeklyMsgForUser = `-- name: GetWeeklyMsgForUser :one
SELECT COALESCE((SELECT messages FROM weekly_xp WHERE guildId = ?1 AND userId = ?2 AND yearWeek = ?3), 0) AS msg_count
`

type GetWeeklyMsgForUserParams struct {
	GuildId  string `json:"guildId"`
	UserId   string `json:"userId"`
	YearWeek string `json:"yearWeek"`
}

func (q *Queries) GetWeeklyMsgForUser(ctx context.Context, arg GetWeeklyMsgForUserParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getWeeklyMsgForUser, arg.GuildId, arg.UserId, arg.YearWeek)
	var msg_count interface{}
	err := row.Scan(&msg_count)
	return msg_count, err
}

const getWeeklyMsgLeaderboard = `-- name: GetWeeklyMsgLeaderboard :many
SELECT userId, messages as count FROM weekly_xp WHERE guildId = ?1 AND yearWeek = ?2 ORDER BY messages DESC LIMIT ?4 OFFSET ?3
`

type GetWeeklyMsgLeaderboardParams struct {
	GuildId  string `json:"guildId"`
	YearWeek string `json:"yearWeek"`
	Offset   int64  `json:"offset"`
	Limit    int64  `json:"limit"`
}

type GetWeeklyMsgLeaderboardRow struct {
	Userid string `json:"userid"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetWeeklyMsgLeaderboard(ctx context.Context, arg GetWeeklyMsgLeaderboardParams) ([]GetWeeklyMsgLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getWeeklyMsgLeaderboard,
		arg.GuildId,
		arg.YearWeek,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWeeklyMsgLeaderboardRow
	for rows.Next() {
		var i GetWeeklyMsgLeaderboardRow
		if err := rows.Scan(&i.Userid, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklyMsgRank = `-- name: GetWeeklyMsgRank :one
SELECT COUNT(*) + 1 AS position FROM weekly_xp AS outer_t WHERE outer_t.yearWeek = ?1 AND outer_t.messages > COALESCE((SELECT messages FROM weekly_xp AS inner_t WHERE inner_t.guildId = ?2 AND inner_t.userId = ?3 AND inner_t.yearWeek = outer_t.yearWeek), 0)
`

type GetWeeklyMsgRankParams struct {
	YearWeek string `json:"yearWeek"`
	GuildId  string `json:"guildId"`
	UserId   string `json:"userId"`
}

func (q *Queries) GetWeeklyMsgRank(ctx context.Context, arg GetWeeklyMsgRankParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWeeklyMsgRank, arg.YearWeek, arg.GuildId, arg.UserId)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const getWeeklyVCForUser = `-- name: GetWeeklyVCForUser :one
SELECT COALESCE((SELECT voiceMinutes FROM weekly_xp WHERE guildId = ?1 AND userId = ?2 AND yearWeek = ?3), 0) AS vc_minutes
`

type GetWeeklyVCForUserParams struct {
	GuildId  string `json:"guildId"`
	UserId   string `json:"userId"`
	YearWeek string `json:"yearWeek"`
}

func (q *Queries) GetWeeklyVCForUser(ctx context.Context, arg GetWeeklyVCForUserParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getWeeklyVCForUser, arg.GuildId, arg.UserId, arg.YearWeek)
	var vc_minutes interface{}
	err := row.Scan(&vc_minutes)
	return vc_minutes, err
}

const getWeeklyVCLeaderboard = `-- name: GetWeeklyVCLeaderboard :many
SELECT userId, voiceMinutes as minutes FROM weekly_xp WHERE guildId = ?1 AND yearWeek = ?2 ORDER BY voiceMinutes DESC LIMIT ?4 OFFSET ?3
`

type GetWeeklyVCLeaderboardParams struct {
	GuildId  string `json:"guildId"`
	YearWeek string `json:"yearWeek"`
	Offset   int64  `json:"offset"`
	Limit    int64  `json:"limit"`
}

type GetWeeklyVCLeaderboardRow struct {
	Userid  string `json:"userid"`
	Minutes int64  `json:"minutes"`
}

func (q *Queries) GetWeeklyVCLeaderboard(ctx context.Context, arg GetWeeklyVCLeaderboardParams) ([]GetWeeklyVCLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getWeeklyVCLeaderboard,
		arg.GuildId,
		arg.YearWeek,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWeeklyVCLeaderboardRow
	for rows.Next() {
		var i GetWeeklyVCLeaderboardRow
		if err := rows.Scan(&i.Userid, &i.Minutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklyVCRank = `-- name: GetWeeklyVCRank :one
SELECT COUNT(*) + 1 AS position FROM weekly_xp AS outer_t WHERE outer_t.yearWeek = ?1 AND outer_t.voiceMinutes > COALESCE((SELECT voiceMinutes FROM weekly_xp AS inner_t WHERE inner_t.guildId = ?2 AND inner_t.userId = ?3 AND inner_t.yearWeek = outer_t.yearWeek), 0)
`

type GetWeeklyVCRankParams struct {
	YearWeek string `json:"yearWeek"`
	GuildId  string `json:"guildId"`
	UserId   string `json:"userId"`
}

func (q *Queries) GetWeeklyVCRank(ctx context.Context, arg GetWeeklyVCRankParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWeeklyVCRank, arg.YearWeek, arg.GuildId, arg.UserId)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const incrementWeeklyVoice = `-- name: IncrementWeeklyVoice :exec
INSERT INTO weekly_xp (guildId, userId, yearWeek, voiceMinutes) VALUES (?1, ?2, ?3, 1) ON CONFLICT (guildId, userId, yearWeek) DO UPDATE SET voiceMinutes = voiceMinutes + 1
`

type IncrementWeeklyVoiceParams struct {
	GuildId  string `json:"guildId"`
	UserId   string `json:"userId"`
	YearWeek string `json:"yearWeek"`
}

func (q *Queries) IncrementWeeklyVoice(ctx context.Context, arg IncrementWeeklyVoiceParams) error {
	_, err := q.db.ExecContext(ctx, incrementWeeklyVoice, arg.GuildId, arg.UserId, arg.YearWeek)
	return err
}

const upsertWeeklyMessage = `-- name: UpsertWeeklyMessage :exec
INSERT INTO weekly_xp (guildId, userId, yearWeek, messages) VALUES (?1, ?2, ?3, 1) ON CONFLICT (guildId, userId, yearWeek) DO UPDATE SET messages = messages + 1
`

type UpsertWeeklyMessageParams struct {
	GuildId  string `json:"guildId"`
	UserId   string `json:"userId"`
	YearWeek string `json:"yearWeek"`
}

func (q *Queries) UpsertWeeklyMessage(ctx context.Context, arg UpsertWeeklyMessageParams) error {
	_, err := q.db.ExecContext(ctx, upsertWeeklyMessage, arg.GuildId, arg.UserId, arg.YearWeek)
	return err
}
