// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Achievement struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Description      string         `json:"description"`
	Icon             sql.NullString `json:"icon"`
	Category         string         `json:"category"`
	RequirementType  string         `json:"requirement_type"`
	RequirementValue int64          `json:"requirement_value"`
	XpReward         sql.NullInt64  `json:"xp_reward"`
	IsHidden         sql.NullBool   `json:"is_hidden"`
	IsRepeatable     sql.NullBool   `json:"is_repeatable"`
	CreatedAt        time.Time      `json:"created_at"`
}

type AchievementProgress struct {
	UserIDStr          string        `json:"user_id_str"`
	Username           string        `json:"username"`
	AchievementID      string        `json:"achievement_id"`
	Name               string        `json:"name"`
	Description        string        `json:"description"`
	Category           string        `json:"category"`
	ProgressCurrent    sql.NullInt64 `json:"progress_current"`
	ProgressRequired   int64         `json:"progress_required"`
	IsCompleted        sql.NullBool  `json:"is_completed"`
	CompletedAt        sql.NullTime  `json:"completed_at"`
	ProgressPercentage float64       `json:"progress_percentage"`
}

type Blacklist struct {
	GuildID    string       `json:"guild_id"`
	EntityType string       `json:"entity_type"`
	EntityID   string       `json:"entity_id"`
	Reason     string       `json:"reason"`
	AddedBy    string       `json:"added_by"`
	IsHidden   bool         `json:"is_hidden"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	AddedAt    time.Time    `json:"added_at"`
}

type BlacklistAudit struct {
	ID         int64          `json:"id"`
	GuildID    string         `json:"guild_id"`
	EntityType string         `json:"entity_type"`
	EntityID   string         `json:"entity_id"`
	Action     string         `json:"action"`
	Reason     sql.NullString `json:"reason"`
	ActorID    string         `json:"actor_id"`
	CreatedAt  time.Time      `json:"created_at"`
}

type BlacklistsOld struct {
	Guildid  string `json:"guildid"`
	Targetid string `json:"targetid"`
	Type     string `json:"type"`
}

type BotConfig struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Drop struct {
	ID        int64         `json:"id"`
	Question  string        `json:"question"`
	Answer    string        `json:"answer"`
	XpAmount  int64         `json:"xp_amount"`
	WinnerID  sql.NullInt64 `json:"winner_id"`
	DroppedBy sql.NullInt64 `json:"dropped_by"`
	ChannelID int64         `json:"channel_id"`
	MessageID sql.NullInt64 `json:"message_id"`
	ClaimedAt sql.NullTime  `json:"claimed_at"`
	CreatedAt time.Time     `json:"created_at"`
}

type Giveaway struct {
	ID              int64         `json:"id"`
	ChannelID       int64         `json:"channel_id"`
	MessageID       int64         `json:"message_id"`
	Prize           string        `json:"prize"`
	WinnerCount     int64         `json:"winner_count"`
	RequiredRole    sql.NullInt64 `json:"required_role"`
	HostID          int64         `json:"host_id"`
	EndsAt          time.Time     `json:"ends_at"`
	Ended           bool          `json:"ended"`
	MinLevel        int64         `json:"min_level"`
	MinAccountDays  int64         `json:"min_account_days"`
	RoleMultipliers string        `json:"role_multipliers"`
	CreatedAt       time.Time     `json:"created_at"`
}

type GiveawayEntry struct {
	GiveawayID int64     `json:"giveaway_id"`
	UserID     int64     `json:"user_id"`
	EnteredAt  time.Time `json:"entered_at"`
}

type GuildLeaderboard struct {
	GuildID     int64          `json:"guild_id"`
	GuildName   sql.NullString `json:"guild_name"`
	UserIDStr   string         `json:"user_id_str"`
	Username    sql.NullString `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	Level       int64          `json:"level"`
	Xp          int64          `json:"xp"`
	MsgAlltime  int64          `json:"msg_alltime"`
	VcAlltime   int64          `json:"vc_alltime"`
	GuildRank   interface{}    `json:"guild_rank"`
}

type GuildSetting struct {
	GuildID               string          `json:"guild_id"`
	GuildName             sql.NullString  `json:"guild_name"`
	XpMultiplier          sql.NullFloat64 `json:"xp_multiplier"`
	VoiceXpPerMinute      sql.NullInt64   `json:"voice_xp_per_minute"`
	MessageXpPerWord      sql.NullInt64   `json:"message_xp_per_word"`
	MaxDailyXp            sql.NullInt64   `json:"max_daily_xp"`
	LevelUpNotifications  sql.NullBool    `json:"level_up_notifications"`
	AnnouncementChannelID sql.NullString  `json:"announcement_channel_id"`
	IgnoredChannels       sql.NullString  `json:"ignored_channels"`
	IgnoredRoles          sql.NullString  `json:"ignored_roles"`
	CustomLevelRoles      sql.NullString  `json:"custom_level_roles"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

type LeaderboardSnapshot struct {
	ID           int64     `json:"id"`
	GuildID      string    `json:"guild_id"`
	SnapshotDate time.Time `json:"snapshot_date"`
	TopUsers     string    `json:"top_users"`
	TotalUsers   int64     `json:"total_users"`
	TotalXp      int64     `json:"total_xp"`
	CreatedAt    time.Time `json:"created_at"`
}

type Level struct {
	Level          int64          `json:"level"`
	LevelName      string         `json:"level_name"`
	MinXpRequired  int64          `json:"min_xp_required"`
	MaxXpRange     int64          `json:"max_xp_range"`
	LevelColor     sql.NullString `json:"level_color"`
	LevelIcon      sql.NullString `json:"level_icon"`
	Rewards        sql.NullString `json:"rewards"`
	Permissions    sql.NullString `json:"permissions"`
	IsSpecialLevel sql.NullBool   `json:"is_special_level"`
	CreatedAt      time.Time      `json:"created_at"`
}

type MessageActivity struct {
	ID            int64         `json:"id"`
	UserIDStr     string        `json:"user_id_str"`
	GuildID       string        `json:"guild_id"`
	ChannelID     string        `json:"channel_id"`
	MessageID     string        `json:"message_id"`
	ContentLength int64         `json:"content_length"`
	WordCount     int64         `json:"word_count"`
	XpEarned      sql.NullInt64 `json:"xp_earned"`
	ActivityDate  time.Time     `json:"activity_date"`
	CreatedAt     time.Time     `json:"created_at"`
}

type Multiplier struct {
	EntityType string  `json:"entity_type"`
	EntityID   int64   `json:"entity_id"`
	Multiplier float64 `json:"multiplier"`
}

type MultipliersOld struct {
	Guildid    string  `json:"guildid"`
	Targetid   string  `json:"targetid"`
	Type       string  `json:"type"`
	Multiplier float64 `json:"multiplier"`
}

type OldUsersCompatible struct {
	Guildid string `json:"guildid"`
	Userid  string `json:"userid"`
	Xp      int64  `json:"xp"`
}

type SystemEvent struct {
	ID        int64          `json:"id"`
	EventType string         `json:"event_type"`
	UserIDStr sql.NullString `json:"user_id_str"`
	GuildID   sql.NullString `json:"guild_id"`
	EventData sql.NullString `json:"event_data"`
	CreatedAt time.Time      `json:"created_at"`
}

type UserAchievement struct {
	ID               int64         `json:"id"`
	UserIDStr        string        `json:"user_id_str"`
	AchievementID    string        `json:"achievement_id"`
	ProgressCurrent  sql.NullInt64 `json:"progress_current"`
	ProgressRequired int64         `json:"progress_required"`
	IsCompleted      sql.NullBool  `json:"is_completed"`
	CompletedAt      sql.NullTime  `json:"completed_at"`
	CompletionCount  sql.NullInt64 `json:"completion_count"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
}

type UserProfile struct {
	UserIDStr         string         `json:"user_id_str"`
	Username          string         `json:"username"`
	DisplayName       sql.NullString `json:"display_name"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	IsBot             sql.NullBool   `json:"is_bot"`
	IsActive          sql.NullBool   `json:"is_active"`
	Bio               sql.NullString `json:"bio"`
	FavoriteColor     sql.NullString `json:"favorite_color"`
	BannerUrl         sql.NullString `json:"banner_url"`
	ReputationScore   sql.NullInt64  `json:"reputation_score"`
	TotalCommandsUsed sql.NullInt64  `json:"total_commands_used"`
	PreferredLanguage sql.NullString `json:"preferred_language"`
	TimezoneOffset    sql.NullInt64  `json:"timezone_offset"`
	FirstSeenAt       time.Time      `json:"first_seen_at"`
	LastSeenAt        time.Time      `json:"last_seen_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type UserRanking struct {
	UserID      int64          `json:"user_id"`
	GuildID     int64          `json:"guild_id"`
	UserIDStr   string         `json:"user_id_str"`
	Xp          int64          `json:"xp"`
	Level       int64          `json:"level"`
	MsgAlltime  int64          `json:"msg_alltime"`
	VcAlltime   int64          `json:"vc_alltime"`
	Username    sql.NullString `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	GlobalRank  interface{}    `json:"global_rank"`
	GuildRank   interface{}    `json:"guild_rank"`
}

type UsersOld struct {
	Guildid string `json:"guildid"`
	Userid  string `json:"userid"`
	Xp      int64  `json:"xp"`
}

type UsersXp struct {
	UserID     int64        `json:"user_id"`
	GuildID    int64        `json:"guild_id"`
	UserIDStr  string       `json:"user_id_str"`
	Xp         int64        `json:"xp"`
	Level      int64        `json:"level"`
	MsgAlltime int64        `json:"msg_alltime"`
	VcAlltime  int64        `json:"vc_alltime"`
	LastMsgAt  sql.NullTime `json:"last_msg_at"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

type VoiceActivity struct {
	ID              int64         `json:"id"`
	UserIDStr       string        `json:"user_id_str"`
	GuildID         string        `json:"guild_id"`
	ChannelID       string        `json:"channel_id"`
	SessionStart    time.Time     `json:"session_start"`
	SessionEnd      sql.NullTime  `json:"session_end"`
	DurationMinutes int64         `json:"duration_minutes"`
	XpEarned        sql.NullInt64 `json:"xp_earned"`
	ActivityDate    time.Time     `json:"activity_date"`
	CreatedAt       time.Time     `json:"created_at"`
}

type WeeklyMessage struct {
	UserID    int64  `json:"user_id"`
	WeekStart string `json:"week_start"`
	Count     int64  `json:"count"`
}

type WeeklyVoice struct {
	UserID    int64  `json:"user_id"`
	WeekStart string `json:"week_start"`
	Minutes   int64  `json:"minutes"`
}

type WeeklyXp struct {
	Guildid      string `json:"guildid"`
	Userid       string `json:"userid"`
	Yearweek     string `json:"yearweek"`
	Xp           int64  `json:"xp"`
	Messages     int64  `json:"messages"`
	Voiceminutes int64  `json:"voiceminutes"`
}

type XpBonuse struct {
	ID        int64          `json:"id"`
	UserIDStr string         `json:"user_id_str"`
	GuildID   sql.NullString `json:"guild_id"`
	Amount    int64          `json:"amount"`
	Reason    string         `json:"reason"`
	GivenBy   sql.NullString `json:"given_by"`
	CreatedAt time.Time      `json:"created_at"`
}

type XpMultipliersEnhanced struct {
	ID         int64          `json:"id"`
	GuildID    sql.NullString `json:"guild_id"`
	UserIDStr  sql.NullString `json:"user_id_str"`
	ChannelID  sql.NullString `json:"channel_id"`
	RoleID     sql.NullString `json:"role_id"`
	EventType  string         `json:"event_type"`
	Multiplier float64        `json:"multiplier"`
	Reason     sql.NullString `json:"reason"`
	StartsAt   time.Time      `json:"starts_at"`
	EndsAt     sql.NullTime   `json:"ends_at"`
	IsActive   sql.NullBool   `json:"is_active"`
	CreatedAt  time.Time      `json:"created_at"`
}
