// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: multipliers.sql

package db

import (
	"context"
)

const getMultiplier = `-- name: GetMultiplier :one
SELECT multiplier FROM multipliers WHERE entity_id = ?1 AND entity_type = ?2
`

type GetMultiplierParams struct {
	EntityId   int64  `json:"entityId"`
	EntityType string `json:"entityType"`
}

func (q *Queries) GetMultiplier(ctx context.Context, arg GetMultiplierParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getMultiplier, arg.EntityId, arg.EntityType)
	var multiplier float64
	err := row.Scan(&multiplier)
	return multiplier, err
}

const listMultipliers = `-- name: ListMultipliers :many
SELECT entity_type, entity_id, multiplier
FROM multipliers ORDER BY entity_type, multiplier DESC
`

func (q *Queries) ListMultipliers(ctx context.Context) ([]Multiplier, error) {
	rows, err := q.db.QueryContext(ctx, listMultipliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Multiplier
	for rows.Next() {
		var i Multiplier
		if err := rows.Scan(&i.EntityType, &i.EntityID, &i.Multiplier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMultiplier = `-- name: RemoveMultiplier :exec
DELETE FROM multipliers WHERE entity_id = ?1
`

func (q *Queries) RemoveMultiplier(ctx context.Context, entityid int64) error {
	_, err := q.db.ExecContext(ctx, removeMultiplier, entityid)
	return err
}

const setMultiplier = `-- name: SetMultiplier :exec
INSERT INTO multipliers (entity_type, entity_id, multiplier) VALUES (?1, ?2, ?3) ON CONFLICT (entity_type, entity_id) DO UPDATE SET multiplier = excluded.multiplier
`

type SetMultiplierParams struct {
	EntityType string  `json:"entityType"`
	TargetId   int64   `json:"targetId"`
	Multiplier float64 `json:"multiplier"`
}

func (q *Queries) SetMultiplier(ctx context.Context, arg SetMultiplierParams) error {
	_, err := q.db.ExecContext(ctx, setMultiplier, arg.EntityType, arg.TargetId, arg.Multiplier)
	return err
}
