// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddAuditLog(ctx context.Context, arg AddAuditLogParams) error
	AddBlacklist(ctx context.Context, arg AddBlacklistParams) error
	AddXPDelta(ctx context.Context, arg AddXPDeltaParams) (UsersXp, error)
	BatchIncrementCounters(ctx context.Context, arg BatchIncrementCountersParams) error
	ClaimDrop(ctx context.Context, arg ClaimDropParams) (Drop, error)
	CountEntries(ctx context.Context, giveawayID int64) (int64, error)
	DeleteEntriesForGiveaway(ctx context.Context, giveawayID int64) error
	DeleteGiveaway(ctx context.Context, id int64) error
	EndGiveaway(ctx context.Context, id int64) error
	GetActiveGiveawayByMessage(ctx context.Context, messageID int64) (Giveaway, error)
	GetAllTimeMsgLeaderboard(ctx context.Context, arg GetAllTimeMsgLeaderboardParams) ([]GetAllTimeMsgLeaderboardRow, error)
	GetAllTimeMsgRank(ctx context.Context, arg GetAllTimeMsgRankParams) (int64, error)
	GetAllTimeVCLeaderboard(ctx context.Context, arg GetAllTimeVCLeaderboardParams) ([]GetAllTimeVCLeaderboardRow, error)
	GetAllTimeVCRank(ctx context.Context, arg GetAllTimeVCRankParams) (int64, error)
	GetAllTimeXPLeaderboard(ctx context.Context, arg GetAllTimeXPLeaderboardParams) ([]GetAllTimeXPLeaderboardRow, error)
	GetAuditLogs(ctx context.Context, arg GetAuditLogsParams) ([]BlacklistAudit, error)
	GetBlacklistDetails(ctx context.Context, arg GetBlacklistDetailsParams) (Blacklist, error)
	GetConfig(ctx context.Context, key string) (string, error)
	GetDrop(ctx context.Context, id int64) (Drop, error)
	GetGiveaway(ctx context.Context, id int64) (Giveaway, error)
	GetGiveawayByMessage(ctx context.Context, messageID int64) (Giveaway, error)
	GetGuildLeaderboard(ctx context.Context, arg GetGuildLeaderboardParams) ([]GetGuildLeaderboardRow, error)
	GetGuildUserStats(ctx context.Context, arg GetGuildUserStatsParams) (UsersXp, error)
	GetMultiplier(ctx context.Context, arg GetMultiplierParams) (float64, error)
	GetPendingDropByMessage(ctx context.Context, messageID sql.NullInt64) (Drop, error)
	GetServerRank(ctx context.Context, arg GetServerRankParams) (int64, error)
	GetTop100Levels(ctx context.Context) ([]GetTop100LevelsRow, error)
	GetUser(ctx context.Context, arg GetUserParams) (UsersXp, error)
	GetWeeklyMsgForUser(ctx context.Context, arg GetWeeklyMsgForUserParams) (interface{}, error)
	GetWeeklyMsgLeaderboard(ctx context.Context, arg GetWeeklyMsgLeaderboardParams) ([]GetWeeklyMsgLeaderboardRow, error)
	GetWeeklyMsgRank(ctx context.Context, arg GetWeeklyMsgRankParams) (int64, error)
	GetWeeklyVCForUser(ctx context.Context, arg GetWeeklyVCForUserParams) (interface{}, error)
	GetWeeklyVCLeaderboard(ctx context.Context, arg GetWeeklyVCLeaderboardParams) ([]GetWeeklyVCLeaderboardRow, error)
	GetWeeklyVCRank(ctx context.Context, arg GetWeeklyVCRankParams) (int64, error)
	HasEntry(ctx context.Context, arg HasEntryParams) (bool, error)
	IncrementMessageCount(ctx context.Context, arg IncrementMessageCountParams) error
	IncrementVoiceMinutes(ctx context.Context, arg IncrementVoiceMinutesParams) error
	IncrementVoiceXP(ctx context.Context, arg IncrementVoiceXPParams) (UsersXp, error)
	IncrementWeeklyVoice(ctx context.Context, arg IncrementWeeklyVoiceParams) error
	InsertDrop(ctx context.Context, arg InsertDropParams) (Drop, error)
	InsertEntry(ctx context.Context, arg InsertEntryParams) error
	InsertGiveaway(ctx context.Context, arg InsertGiveawayParams) (Giveaway, error)
	ListActive(ctx context.Context) ([]Giveaway, error)
	ListEntries(ctx context.Context, giveawayID int64) ([]int64, error)
	ListExpiredUnended(ctx context.Context) ([]Giveaway, error)
	ListGuildBlacklist(ctx context.Context, arg ListGuildBlacklistParams) ([]Blacklist, error)
	ListMultipliers(ctx context.Context) ([]Multiplier, error)
	PruneExpiredBlacklists(ctx context.Context) (int64, error)
	RemoveBlacklist(ctx context.Context, arg RemoveBlacklistParams) error
	RemoveMultiplier(ctx context.Context, entityid int64) error
	SetConfig(ctx context.Context, arg SetConfigParams) error
	SetMultiplier(ctx context.Context, arg SetMultiplierParams) error
	SetUserXPAndLevel(ctx context.Context, arg SetUserXPAndLevelParams) (UsersXp, error)
	UpdateGiveawayMessage(ctx context.Context, arg UpdateGiveawayMessageParams) error
	UpdateUserLevel(ctx context.Context, arg UpdateUserLevelParams) error
	UpsertUserXP(ctx context.Context, arg UpsertUserXPParams) (UsersXp, error)
	UpsertWeeklyMessage(ctx context.Context, arg UpsertWeeklyMessageParams) error
}

var _ Querier = (*Queries)(nil)
