// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const addXPDelta = `-- name: AddXPDelta :one
INSERT INTO users_xp (guild_id, user_id_str, xp, level, msg_alltime, vc_alltime, created_at, updated_at)
VALUES (?1, ?2, ?3, 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (guild_id, user_id_str) DO UPDATE SET
    xp = xp + excluded.xp,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, guild_id, user_id_str, xp, level, msg_alltime, vc_alltime, last_msg_at, created_at, updated_at
`

type AddXPDeltaParams struct {
	GuildId int64  `json:"guildId"`
	UserId  string `json:"userId"`
	Xp      int64  `json:"xp"`
}

func (q *Queries) AddXPDelta(ctx context.Context, arg AddXPDeltaParams) (UsersXp, error) {
	row := q.db.QueryRowContext(ctx, addXPDelta, arg.GuildId, arg.UserId, arg.Xp)
	var i UsersXp
	err := row.Scan(
		&i.UserID,
		&i.GuildID,
		&i.UserIDStr,
		&i.Xp,
		&i.Level,
		&i.MsgAlltime,
		&i.VcAlltime,
		&i.LastMsgAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const batchIncrementCounters = `-- name: BatchIncrementCounters :exec
UPDATE users_xp
SET
    msg_alltime = CASE WHEN ?1 = 1 THEN msg_alltime + 1 ELSE msg_alltime END,
    vc_alltime = CASE WHEN ?2 = 1 THEN vc_alltime + 1 ELSE vc_alltime END,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id_str = ?3 AND guild_id = ?4
`

type BatchIncrementCountersParams struct {
	IncrementMsg interface{} `json:"incrementMsg"`
	IncrementVC  interface{} `json:"incrementVC"`
	UserId       string      `json:"userId"`
	GuildId      int64       `json:"guildId"`
}

func (q *Queries) BatchIncrementCounters(ctx context.Context, arg BatchIncrementCountersParams) error {
	_, err := q.db.ExecContext(ctx, batchIncrementCounters,
		arg.IncrementMsg,
		arg.IncrementVC,
		arg.UserId,
		arg.GuildId,
	)
	return err
}

const getAllTimeMsgLeaderboard = `-- name: GetAllTimeMsgLeaderboard :many
SELECT user_id_str, msg_alltime FROM users_xp ORDER BY msg_alltime DESC LIMIT ?2 OFFSET ?1
`

type GetAllTimeMsgLeaderboardParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type GetAllTimeMsgLeaderboardRow struct {
	UserIDStr  string `json:"user_id_str"`
	MsgAlltime int64  `json:"msg_alltime"`
}

func (q *Queries) GetAllTimeMsgLeaderboard(ctx context.Context, arg GetAllTimeMsgLeaderboardParams) ([]GetAllTimeMsgLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTimeMsgLeaderboard, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTimeMsgLeaderboardRow
	for rows.Next() {
		var i GetAllTimeMsgLeaderboardRow
		if err := rows.Scan(&i.UserIDStr, &i.MsgAlltime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTimeMsgRank = `-- name: GetAllTimeMsgRank :one
SELECT COUNT(*) + 1 AS position FROM users_xp
WHERE msg_alltime > (SELECT ux.msg_alltime FROM users_xp ux WHERE ux.user_id_str = ?1 AND ux.guild_id = ?2)
`

type GetAllTimeMsgRankParams struct {
	UserId  string `json:"userId"`
	GuildId int64  `json:"guildId"`
}

func (q *Queries) GetAllTimeMsgRank(ctx context.Context, arg GetAllTimeMsgRankParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAllTimeMsgRank, arg.UserId, arg.GuildId)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const getAllTimeVCLeaderboard = `-- name: GetAllTimeVCLeaderboard :many
SELECT user_id_str, vc_alltime FROM users_xp ORDER BY vc_alltime DESC LIMIT ?2 OFFSET ?1
`

type GetAllTimeVCLeaderboardParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type GetAllTimeVCLeaderboardRow struct {
	UserIDStr string `json:"user_id_str"`
	VcAlltime int64  `json:"vc_alltime"`
}

func (q *Queries) GetAllTimeVCLeaderboard(ctx context.Context, arg GetAllTimeVCLeaderboardParams) ([]GetAllTimeVCLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTimeVCLeaderboard, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTimeVCLeaderboardRow
	for rows.Next() {
		var i GetAllTimeVCLeaderboardRow
		if err := rows.Scan(&i.UserIDStr, &i.VcAlltime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTimeVCRank = `-- name: GetAllTimeVCRank :one
SELECT COUNT(*) + 1 AS position FROM users_xp
WHERE vc_alltime > (SELECT ux.vc_alltime FROM users_xp ux WHERE ux.user_id_str = ?1 AND ux.guild_id = ?2)
`

type GetAllTimeVCRankParams struct {
	UserId  string `json:"userId"`
	GuildId int64  `json:"guildId"`
}

func (q *Queries) GetAllTimeVCRank(ctx context.Context, arg GetAllTimeVCRankParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAllTimeVCRank, arg.UserId, arg.GuildId)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const getAllTimeXPLeaderboard = `-- name: GetAllTimeXPLeaderboard :many
SELECT user_id_str, xp, level FROM users_xp ORDER BY level DESC, xp DESC LIMIT ?2 OFFSET ?1
`

type GetAllTimeXPLeaderboardParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type GetAllTimeXPLeaderboardRow struct {
	UserIDStr string `json:"user_id_str"`
	Xp        int64  `json:"xp"`
	Level     int64  `json:"level"`
}

func (q *Queries) GetAllTimeXPLeaderboard(ctx context.Context, arg GetAllTimeXPLeaderboardParams) ([]GetAllTimeXPLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTimeXPLeaderboard, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTimeXPLeaderboardRow
	for rows.Next() {
		var i GetAllTimeXPLeaderboardRow
		if err := rows.Scan(&i.UserIDStr, &i.Xp, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuildLeaderboard = `-- name: GetGuildLeaderboard :many
SELECT user_id_str, xp, level, msg_alltime, vc_alltime
FROM users_xp
WHERE guild_id = ?1
ORDER BY level DESC, xp DESC
LIMIT ?2
`

type GetGuildLeaderboardParams struct {
	GuildId int64 `json:"guildId"`
	Limit   int64 `json:"limit"`
}

type GetGuildLeaderboardRow struct {
	UserIDStr  string `json:"user_id_str"`
	Xp         int64  `json:"xp"`
	Level      int64  `json:"level"`
	MsgAlltime int64  `json:"msg_alltime"`
	VcAlltime  int64  `json:"vc_alltime"`
}

func (q *Queries) GetGuildLeaderboard(ctx context.Context, arg GetGuildLeaderboardParams) ([]GetGuildLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getGuildLeaderboard, arg.GuildId, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGuildLeaderboardRow
	for rows.Next() {
		var i GetGuildLeaderboardRow
		if err := rows.Scan(
			&i.UserIDStr,
			&i.Xp,
			&i.Level,
			&i.MsgAlltime,
			&i.VcAlltime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuildUserStats = `-- name: GetGuildUserStats :one
SELECT user_id, guild_id, user_id_str, xp, level, msg_alltime, vc_alltime, last_msg_at, created_at, updated_at
FROM users_xp
WHERE user_id_str = ?1 AND guild_id = ?2
`

type GetGuildUserStatsParams struct {
	UserId  string `json:"userId"`
	GuildId int64  `json:"guildId"`
}

func (q *Queries) GetGuildUserStats(ctx context.Context, arg GetGuildUserStatsParams) (UsersXp, error) {
	row := q.db.QueryRowContext(ctx, getGuildUserStats, arg.UserId, arg.GuildId)
	var i UsersXp
	err := row.Scan(
		&i.UserID,
		&i.GuildID,
		&i.UserIDStr,
		&i.Xp,
		&i.Level,
		&i.MsgAlltime,
		&i.VcAlltime,
		&i.LastMsgAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServerRank = `-- name: GetServerRank :one
SELECT COUNT(*) + 1 AS position FROM users_xp
WHERE (level > ?1) OR (level = ?1 AND xp > ?2)
`

type GetServerRankParams struct {
	Level int64 `json:"level"`
	Xp    int64 `json:"xp"`
}

func (q *Queries) GetServerRank(ctx context.Context, arg GetServerRankParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getServerRank, arg.Level, arg.Xp)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const getTop100Levels = `-- name: GetTop100Levels :many
SELECT user_id_str, xp, level FROM users_xp ORDER BY level DESC, xp DESC LIMIT 100
`

type GetTop100LevelsRow struct {
	UserIDStr string `json:"user_id_str"`
	Xp        int64  `json:"xp"`
	Level     int64  `json:"level"`
}

func (q *Queries) GetTop100Levels(ctx context.Context) ([]GetTop100LevelsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTop100Levels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTop100LevelsRow
	for rows.Next() {
		var i GetTop100LevelsRow
		if err := rows.Scan(&i.UserIDStr, &i.Xp, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT user_id, guild_id, user_id_str, xp, level, msg_alltime, vc_alltime, last_msg_at, created_at, updated_at
FROM users_xp
WHERE user_id_str = ?1 AND guild_id = ?2
`

type GetUserParams struct {
	UserId  string `json:"userId"`
	GuildId int64  `json:"guildId"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (UsersXp, error) {
	row := q.db.QueryRowContext(ctx, getUser, arg.UserId, arg.GuildId)
	var i UsersXp
	err := row.Scan(
		&i.UserID,
		&i.GuildID,
		&i.UserIDStr,
		&i.Xp,
		&i.Level,
		&i.MsgAlltime,
		&i.VcAlltime,
		&i.LastMsgAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementMessageCount = `-- name: IncrementMessageCount :exec
INSERT INTO users_xp (guild_id, user_id_str, xp, level, msg_alltime, vc_alltime, created_at, updated_at)
VALUES (?1, ?2, 0, 0, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (guild_id, user_id_str) DO UPDATE SET
    msg_alltime = msg_alltime + 1,
    updated_at = CURRENT_TIMESTAMP
`

type IncrementMessageCountParams struct {
	GuildId int64  `json:"guildId"`
	UserId  string `json:"userId"`
}

func (q *Queries) IncrementMessageCount(ctx context.Context, arg IncrementMessageCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementMessageCount, arg.GuildId, arg.UserId)
	return err
}

const incrementVoiceMinutes = `-- name: IncrementVoiceMinutes :exec
INSERT INTO users_xp (guild_id, user_id_str, xp, level, msg_alltime, vc_alltime, created_at, updated_at)
VALUES (?1, ?2, 0, 0, 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (guild_id, user_id_str) DO UPDATE SET
    vc_alltime = vc_alltime + 1,
    updated_at = CURRENT_TIMESTAMP
`

type IncrementVoiceMinutesParams struct {
	GuildId int64  `json:"guildId"`
	UserId  string `json:"userId"`
}

func (q *Queries) IncrementVoiceMinutes(ctx context.Context, arg IncrementVoiceMinutesParams) error {
	_, err := q.db.ExecContext(ctx, incrementVoiceMinutes, arg.GuildId, arg.UserId)
	return err
}

const incrementVoiceXP = `-- name: IncrementVoiceXP :one
INSERT INTO users_xp (guild_id, user_id_str, xp, level, msg_alltime, vc_alltime, created_at, updated_at)
VALUES (?1, ?2, ?3, 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (guild_id, user_id_str) DO UPDATE SET
    xp = xp + excluded.xp,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, guild_id, user_id_str, xp, level, msg_alltime, vc_alltime, last_msg_at, created_at, updated_at
`

type IncrementVoiceXPParams struct {
	GuildId int64  `json:"guildId"`
	UserId  string `json:"userId"`
	Xp      int64  `json:"xp"`
}

func (q *Queries) IncrementVoiceXP(ctx context.Context, arg IncrementVoiceXPParams) (UsersXp, error) {
	row := q.db.QueryRowContext(ctx, incrementVoiceXP, arg.GuildId, arg.UserId, arg.Xp)
	var i UsersXp
	err := row.Scan(
		&i.UserID,
		&i.GuildID,
		&i.UserIDStr,
		&i.Xp,
		&i.Level,
		&i.MsgAlltime,
		&i.VcAlltime,
		&i.LastMsgAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserXPAndLevel = `-- name: SetUserXPAndLevel :one
INSERT INTO users_xp (guild_id, user_id_str, xp, level, msg_alltime, vc_alltime, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (guild_id, user_id_str) DO UPDATE SET
    xp = excluded.xp,
    level = excluded.level,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, guild_id, user_id_str, xp, level, msg_alltime, vc_alltime, last_msg_at, created_at, updated_at
`

type SetUserXPAndLevelParams struct {
	GuildId int64  `json:"guildId"`
	UserId  string `json:"userId"`
	Xp      int64  `json:"xp"`
	Level   int64  `json:"level"`
}

func (q *Queries) SetUserXPAndLevel(ctx context.Context, arg SetUserXPAndLevelParams) (UsersXp, error) {
	row := q.db.QueryRowContext(ctx, setUserXPAndLevel,
		arg.GuildId,
		arg.UserId,
		arg.Xp,
		arg.Level,
	)
	var i UsersXp
	err := row.Scan(
		&i.UserID,
		&i.GuildID,
		&i.UserIDStr,
		&i.Xp,
		&i.Level,
		&i.MsgAlltime,
		&i.VcAlltime,
		&i.LastMsgAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLevel = `-- name: UpdateUserLevel :exec
UPDATE users_xp SET xp = ?1 WHERE user_id_str = ?2 AND guild_id = ?3
`

type UpdateUserLevelParams struct {
	Xp      int64  `json:"xp"`
	UserId  string `json:"userId"`
	GuildId int64  `json:"guildId"`
}

func (q *Queries) UpdateUserLevel(ctx context.Context, arg UpdateUserLevelParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLevel, arg.Xp, arg.UserId, arg.GuildId)
	return err
}

const upsertUserXP = `-- name: UpsertUserXP :one
INSERT INTO users_xp (guild_id, user_id_str, xp, level, msg_alltime, vc_alltime, created_at, updated_at)
VALUES (?1, ?2, ?3, 0, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (guild_id, user_id_str) DO UPDATE SET
    xp = xp + excluded.xp,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, guild_id, user_id_str, xp, level, msg_alltime, vc_alltime, last_msg_at, created_at, updated_at
`

type UpsertUserXPParams struct {
	GuildId int64  `json:"guildId"`
	UserId  string `json:"userId"`
	Xp      int64  `json:"xp"`
}

func (q *Queries) UpsertUserXP(ctx context.Context, arg UpsertUserXPParams) (UsersXp, error) {
	row := q.db.QueryRowContext(ctx, upsertUserXP, arg.GuildId, arg.UserId, arg.Xp)
	var i UsersXp
	err := row.Scan(
		&i.UserID,
		&i.GuildID,
		&i.UserIDStr,
		&i.Xp,
		&i.Level,
		&i.MsgAlltime,
		&i.VcAlltime,
		&i.LastMsgAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
